{"name": "test_vwo_login_positive", "status": "skipped", "statusDetails": {"message": "XFAIL reason: Failed TC\n\n_pytest.outcomes.XFailed: Failed TC", "trace": "@allure.epic(\"VWO Login Test\")\n    @allure.feature(\"TC#1 - VWO App Positive Test\")\n    @pytest.mark.positive\n    def test_vwo_login_positive():\n        try:\n            driver=setup\n            login_page=LoginPage(driver)\n>           login_page.login_to_vwo(user=\"vijayatester16@gmail.com\",pwd=\"Wingify@123\")\n\ntests\\vwoLoginTests\\test_vwo_login.py:44: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntests\\pageObjects\\pom\\loginPage.py:46: in login_to_vwo\n    self.get_username().send_keys(user)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <tests.pageObjects.pom.loginPage.LoginPage object at 0x000002116A620E60>\n\n    def get_username(self):\n>       return self.driver.find_element(*LoginPage.username)\nE       AttributeError: 'function' object has no attribute 'find_element'\n\ntests\\pageObjects\\pom\\loginPage.py:33: AttributeError\n\nDuring handling of the above exception, another exception occurred:\n\n    @allure.epic(\"VWO Login Test\")\n    @allure.feature(\"TC#1 - VWO App Positive Test\")\n    @pytest.mark.positive\n    def test_vwo_login_positive():\n        try:\n            driver=setup\n            login_page=LoginPage(driver)\n            login_page.login_to_vwo(user=\"vijayatester16@gmail.com\",pwd=\"Wingify@123\")\n            time.sleep(10)\n            dashboard=DashboardPage(driver)\n            # assert \"Dashboard\" in driver.title\n            assert \"Web Automation\" in dashboard.user_logged_in_text()\n        except Exception as e:\n>           pytest.xfail(\"Failed TC\")\nE           _pytest.outcomes.XFailed: Failed TC\n\ntests\\vwoLoginTests\\test_vwo_login.py:50: XFailed"}, "start": 1741680837429, "stop": 1741680837430, "uuid": "99961197-0b4c-40db-b6a2-5d4c02011518", "historyId": "99091ff4f3a54bbba7777a96f0a2fe5e", "testCaseId": "99091ff4f3a54bbba7777a96f0a2fe5e", "fullName": "tests.vwoLoginTests.test_vwo_login#test_vwo_login_positive", "labels": [{"name": "feature", "value": "TC#1 - VWO App Positive Test"}, {"name": "epic", "value": "VWO Login Test"}, {"name": "tag", "value": "positive"}, {"name": "parentSuite", "value": "tests.vwoLoginTests"}, {"name": "suite", "value": "test_vwo_login"}, {"name": "host", "value": "LAPTOP-OLURE44J"}, {"name": "thread", "value": "9936-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.vwoLoginTests.test_vwo_login"}]}